# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ada9030cc41da4e68cbe1b84e651779de17a932e37749a23b7f111e7ad46a1cfae62c9e4f0f03bfdc4d6bf0a0f7ef6fed7c77f00ec1898faa7e94fa7fdcf2a87

test:
  secret_key_base: c3fad4741b6dc8949a6224590ce15f076d30c7d6ef8a43c2a2461f7998a63ed65e6e8204272b8419e229386304c4bad83f7f6e92bff1aae384ec127c7798254c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
